spring:
  application:
    name: oauth-two-jwt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 91005058729-3k4hglevrvbq6rltgk9irge8gfvembak.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          naver:
            client-name: naver
            client-id: ulE3cIHkOPrGUrU0QV2Q
            client-secret: u1_vyQ21cn
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, birthday, mobile, birthyear
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalasdrerkljdfksdeccas
  mustache:
    servlet:
      expose-request-attributes: true